name: Dev Pre-release (semantic-release)

on:
  push:
    branches: [main, "release/**"]

jobs:
  dev-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node v22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Run semantic-release
        id: semantic
        uses: codfish/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branches: |
            [
              'release',
              {
                name: 'main',
                prerelease: 'dev'
              }
            ]
          plugins: |
            [
              [
                "@semantic-release/commit-analyzer",
                {
                  "preset": "angular",
                  "releaseRules": [
                    {
                      "type": "refactor",
                      "release": "patch"
                    },
                    {
                      "type": "build",
                      "release": "patch"
                    }
                  ]
                }
              ],
              [
                "@semantic-release/npm",
                {
                  "npmPublish": false
                }
              ],
              "@semantic-release/release-notes-generator",
            ]

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        if: steps.semantic.outputs.new-release-published == 'true'

      - name: Docker login
        uses: docker/login-action@v3
        if: steps.semantic.outputs.new-release-published == 'true'
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_PWD }}

      - name: Build & push dev Docker image
        uses: docker/build-push-action@v6
        if: steps.semantic.outputs.new-release-published == 'true'
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_LOGIN }}/verana-resolver:dev
            ${{ secrets.DOCKER_HUB_LOGIN }}/verana-resolver:v${{ steps.semantic.outputs.release-major }}-dev
            ${{ secrets.DOCKER_HUB_LOGIN }}/verana-resolver:v${{ steps.semantic.outputs.release-major }}.${{ steps.semantic.outputs.release-minor }}-dev
            ${{ secrets.DOCKER_HUB_LOGIN }}/verana-resolver:v${{ steps.semantic.outputs.release-version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Set up Helm
        if: steps.semantic.outputs.new-release-published == 'true'
        uses: azure/setup-helm@v3

      - name: Log in to Docker Hub Helm Registry
        if: steps.semantic.outputs.new-release-published == 'true'
        run: |
          echo "${{ secrets.DOCKER_HUB_PWD }}" | helm registry login -u "${{ secrets.DOCKER_HUB_LOGIN }}" --password-stdin docker.io

      - name: Push Helm chart to Docker Hub OCI repo
        if: steps.semantic.outputs.new-release-published == 'true'
        run: |
          TAGS=(
            "v${{ steps.semantic.outputs.release-major }}.${{ steps.semantic.outputs.release-minor }}-dev"
            "v${{ steps.semantic.outputs.release-version }}"
          )
          for tag in "${TAGS[@]}"; do
            CHART_NAME=$(grep '^name:' ./charts/Chart.yaml | awk '{print $2}')
            helm dependency update ./charts
            helm package ./charts --version $tag -d ./charts
            helm push ./charts/$CHART_NAME-$tag.tgz oci://docker.io/"${{ secrets.DOCKER_HUB_LOGIN }}"
          done

      - name: Publish Summary
        if: steps.semantic.outputs.new-release-published == 'true'
        run: |
          echo "Docker Images" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- verana-resolver:dev" >> $GITHUB_STEP_SUMMARY
          echo "- verana-resolver:v${{ steps.semantic.outputs.release-major }}-dev" >> $GITHUB_STEP_SUMMARY
          echo "- verana-resolver:v${{ steps.semantic.outputs.release-major }}.${{ steps.semantic.outputs.release-minor }}-dev" >> $GITHUB_STEP_SUMMARY
          echo "- verana-resolver:v${{ steps.semantic.outputs.release-version }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Helm Charts" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- verana-resolver-chart:v${{ steps.semantic.outputs.release-major }}.${{ steps.semantic.outputs.release-minor }}-dev" >> $GITHUB_STEP_SUMMARY
          echo "- verana-resolver-chart:v${{ steps.semantic.outputs.release-version }}" >> $GITHUB_STEP_SUMMARY
